{% set name = "macro-kit" %}
{% set version = "0.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cb78a0ba35ab1c2090ba49c1f211037bf95cc0d72433d5fdb0823fefaf4c47f0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<=38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - hatchling
    - pip
    - python
  run:
    - python
    - typing-extensions

test:
  imports:
    - macrokit
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/macro-kit
  summary: Macro recording and metaprogramming in Python
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/hanjinliu/macro-kit

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
