{% set name = "macro-kit" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/macro-kit-{{ version }}.tar.gz
  sha256: d78f7889e4a6c9f6fde7517f93b2ee886b2c87fb1fdcafa2cbaff5ea260d2c2b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - python
    - typing-extensions

test:
  imports:
    - macrokit
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hanjinliu/macro-kit
  summary: Macro recording and metaprogramming in Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
